### ISSUE TITLE
Sorry to open a new issue

### ISSUE THREAD

**Issue by tutyamxx** [flash-oss/node_acl#10]
I don't know how to find/contact you, but could you publish it to npm as well? the recent fix? I'm using it and I need the latest one XD Thanks

**Comment by koresar** [comment]
![image](https://user-images.githubusercontent.com/1622575/163187932-01a1578d-1961-4f75-aa54-a44b1b2bb9f5.png)

Here you go. :)

**Comment by tutyamxx** [comment]
I did see, apologies the npm page was cached and still showed last update 4 months ago. I forced a reload and it updated. Apologies for any inconveniences.
