### ISSUE TITLE
Bluebird to Native Promise?

### ISSUE THREAD

**Issue by kaizen1** [flash-oss/node_acl#12]
Any chance you will be removing Bluebird?
Bluebird is a dead project since node supports Promises natively.

**Comment by koresar** [comment]
I'd love to! Can you do it for us? It should be a straightforward pull request. Except this line:

```
    return bluebird.reduce(demuxed, (values, obj) => this.allow(obj.roles, obj.resources, obj.permissions), null);
```

**Comment by kaizen1** [comment]
Thanks for the response but we're only experimenting a bit with node_acl and noticed dying code i.e. bluebird.
So we can't spend time on it.

**Comment by koresar** [comment]
Someday we'll find a volunteer.
Cheers
