### ISSUE TITLE
Bluebird Dependency

### ISSUE THREAD

**Issue by kaizen1** [flash-oss/node_acl#15]
Bluebird folks are pushing people to move to Promises.
Any plan for this replacement? Or is the project dormant?
I'm a PM so please don't ask me for a PR :)
Thanks.

**Comment by koresar** [comment]
I tried moving to Promises few times. But there are certain APIs (like Defer and Promise.map) which are a bit longer to move. So, I kinda left it as is until someone drops a PR.
I'm a CTO, so please don't tell me you are a PM. :)
Cheers

**Comment by kaizen1** [comment]
CTO / PM are the same thing in a startup :)

**Comment by koresar** [comment]
Exactly.

**Comment by koresar** [comment]
Done: https://github.com/flash-oss/node_acl/releases/tag/v4.0.0
