### ISSUE TITLE
How can I import in Typescript ES6?

### ISSUE THREAD

**Issue by hwooo** [flash-oss/node_acl#16]
```
import * as ACL from 'acl2';
```

![pic1](https://user-images.githubusercontent.com/46282492/209459050-38d28f47-540f-4565-8a89-82b1298c132e.png)

`npm install acl2` has successfully finished but I can't import the module.
Every examples in repository are written in ES5 grammar. How can I use it in TypeScript ES6?

**Comment by koresar** [comment]
TypeScript usage:

```ts
var ACL: any = require("acl2");
```

Tell me how it goes.
