### ISSUE TITLE
MonboDB >v5 driver support

### ISSUE THREAD

**Issue by toni-lahnalampi** [flash-oss/node_acl#17]
Hi, and thanks for your valuable work with this fork!

I noticed, that Mongodb >v5 driver has dropped callback apis and acl2 does not support it yet.

I made an implementation:
https://github.com/tonila/node_acl_firebase/blob/acl2_mongodb_promise_api_backend/lib/mongodb-backend.js

MongoDB tests pass:

```
npm run mongo_test
npm run test_mongo_single
```

I can make a pull request, if requested.

**Comment by koresar** [comment]
Thank you very much. I request!
