### ISSUE TITLE
dynamic assertions?

### ISSUE THREAD

**Issue by scottybe** [flash-oss/node_acl#2]
Hi, and thanks for supporting this library. I have experience with Zend ACL and was comparing this with it.

Does this support the ability for a permission to be determined dynamically? For example, how would I only allow a user with the "editor" role to edit a "document" resource only if he is the document creator?

https://docs.zendframework.com/zend-expressive-authorization-rbac/v1/dynamic-assertion/

Thanks!

**Comment by koresar** [comment]
Hello @scottybe 
None of us is familiar with Zend ACL.

But answering your question I believe that the answer should be "Yes".
But I have no idea what would be the JS code for that.

Sorry. There is not much help you can get from us.
