### ISSUE TITLE
Add types

### ISSUE THREAD

**Issue by charbelsako** [flash-oss/node_acl#21]
So I came across this package because at my job our code still runs `acl` which hasn't been updated since forever

I wanted to try and update the code base to use `node v22` and use `typescript` at the same time, which is something I tried to do with the original `acl` library and didn't work

But I ran into an issue with the `tsserver` showing errors that no types were defined
I know there are ways around this and I could run this package without types at all which I did do but then for fun I tried writing types myself, I only wrote for two functions, and this is the first time I'm writing types at all so take it with a grain of salt

```
declare module "acl2" {
  import { Db } from "mongodb";
  interface RolePermission {
    roles: string | string[];
    allows: {
      resources: string | string[];
      permissions: string | string[];
    }[];
  }

  class Acl {
    constructor(backend: Acl.MongoBackend);

    allow(rolesPermissions: RolePermission[]): void;
  }

  namespace Acl {
    interface MongoBackend {
      new (db: Db, prefix: string): Acl;
    }
    function mongodbBackend(db: Db, prefix: string): void;
  }

  // Export the ACL class for use
  export = Acl;
}
```

is this something you might add in the future?

**Comment by koresar** [comment]
Hi @charbelsako 
I'm happy to merge a PR with types. Feel free to submit.
Thanks for bringing this up.

**Comment by charbelsako** [comment]
I honestly don't know how to start
do I just add `index.d.ts` and add types

**Comment by charbelsako** [comment]
I'm not sure if I did it correctly I just added `index.d.ts` to the fork, I tested by adding the same file into `node_modules` gotta be honest though Chat GPT did most of the work
