### ISSUE TITLE
Missing index on `key` property on Mongodb

### ISSUE THREAD

**Issue by gkampitakis** [flash-oss/node_acl#4]
I created[ an issue](https://github.com/OptimalBits/node_acl/issues/291) to the original repository just in case someone has the same issue. What was noticed is that the library creates an index https://github.com/flash-oss/node_acl/blob/966d079e3a2cda9a8243400e29fde857b0349c11/lib/mongodb-backend.js#L145 and then in the case of the `useSingle=false` we are not using this index as we are querying with just the `key` meaning we are not using the index resulting to slow queries. Maybe the index could respect the `useSingle` flag and create the correct index.

https://github.com/flash-oss/node_acl/blob/966d079e3a2cda9a8243400e29fde857b0349c11/lib/mongodb-backend.js#L121

**Comment by koresar** [comment]
Sound like a good idea.
Would you please a PR? We love PRs!

**Comment by gkampitakis** [comment]
I am happy to 😄 , I will try to work on it today and send a pr

**Comment by koresar** [comment]
Thanks! Sorry for the delay. PR reviewed, merged, published as v2.0.1
