### ISSUE TITLE
Annoying duplicates error

### ISSUE THREAD

**Issue by tutyamxx** [flash-oss/node_acl#8]
I get this: `insert into "acl_permissions" ("key", "value") values ($1, $2) - duplicate key value violates unique constraint "acl_permissions_pkey"` when I try to create (using `acl.allow`) two identical roles, but with different names, and different permissions BUT the same resources. How do I even deal with this? 😕

**Comment by zelucena** [comment]
If that's just a SQL thing, `insert ignore into "acl_permissions" ("key", "value") values ($1, $2)` should do the trick.
