### ISSUE TITLE
Vulnerability to prototype pollution in async

### ISSUE THREAD

**Issue by tutyamxx** [flash-oss/node_acl#9]
https://github.com/advisories/GHSA-fwr7-v2mv-hh25

**Comment by koresar** [comment]
Fixed. Published as v3.0.1

**Comment by tutyamxx** [comment]
Thank you kindly. Please make sure you publish it to npm (if you don't have the automatic package publisher set up). Thanks again.

**Comment by koresar** [comment]
Mate. Take a look a my message above. Does it answer your question?

**Comment by tutyamxx** [comment]
I did, apologies the npm page was cached and still showed last update 4 months ago. I forced a reload and it updated. Apologies for any inconveniences.
